const CATALOG = [
{"id": "el_1", "type": "Cassette", "genre":"Rock90", "name": "OK Computer", "img": "img/cassettes/okcomputer_front.jpg", "price": "300 рублей"},
{"id": "el_2", "type": "Cassette", "genre":"Rock90", "name": "In Utero", "img": "img/cassettes/inutero_front.jpg", "price": "250 рублей"},
{"id": "el_3", "type": "Cassette", "genre":"Rock90", "name": "Dolittle", "img": "img/cassettes/dolittle_front.jpg", "price": "375 рублей"},
{"id": "el_4", "type": "Cassette", "genre":"Rock90", "name": "Automatic For The People", "img": "img/cassettes/automaticforthepeople_front.jpg", "price": "215 рублей"},
{"id": "el_5", "type": "Cassette", "genre":"Rock90", "name": "Doo", "img": "img/cassettes/goo_front.jpg", "price": "263 рублей"},
{"id": "el_6", "type": "Cassette", "genre":"Rock90", "name": "Dookie", "img": "img/cassettes/dookie_front.jpg", "price": "175 рублей"},
{"id": "el_7", "type": "Cassette", "genre":"Rock90", "name": "The Bends", "img": "img/cassettes/bends_front.jpg", "price": "398 Рублей"},
{"id": "el_8", "type": "Cassette", "genre":"Rock90", "name": "Bleach", "img": "img/cassettes/bleach_front.jpg", "price": "112 рублей"},
{"id": "el_9", "type": "Cassette", "genre":"Rock90", "name": "Last Splash", "img": "img/cassettes/lastsplash_front.jpg", "price": "86 рублей"},
{"id": "el_10", "type": "Cassette", "genre":"Rock90", "name": "Rage Against The Machine", "img": "img/cassettes/rageagainstmachine_front.jpg", "price": "134 рублей"},
{"id": "el_11", "type": "Cassette", "genre":"Rap", "name": "The Enimem Show", "img": "img/cassettes/theenimemshow_front.jpg", "price": "450 рублей"},
{"id": "el_12", "type": "Cassette", "genre":"Rap", "name": "The Chronic", "img": "img/cassettes/thechronic_front.jpg", "price": "320 рублей"},
{"id": "el_13", "type": "Cassette", "genre":"Rap", "name": "Ready To Die", "img": "img/cassettes/readytodie_front.jpg", "price": "407 рублей"},
{"id": "el_14", "type": "Cassette", "genre":"Rap", "name": "The Slim Shady LP", "img": "img/cassettes/theslimshadylp_front.jpg", "price": "125 рублей"},
{"id": "el_15", "type": "Cassette", "genre":"Rap", "name": "Reasonable Doubt", "img": "img/cassettes/reasonabledoubt_front.jpg", "price": "246 рублей"},
{"id": "el_16", "type": "Cassette", "genre":"Blues", "name": "Robert Johnson", "img": "img/cassettes/rj_front.jpg", "price": "145 рублей"},
{"id": "el_17", "type": "Cassette", "genre":"Blues", "name": "Muddy Waters", "img": "img/cassettes/muddy_front.jpg", "price": "197 рублей"},
{"id": "el_18", "type": "Cassette", "genre":"El", "name": "The Fat Of The Land", "img": "img/cassettes/fatoftheland_front.jpg", "price": "600 рублей"},
{"id": "el_19", "type": "Cassette", "genre":"El", "name": "Play", "img": "img/cassettes/play_front.jpg", "price": "245 рублей"},
{"id": "el_20", "type": "Cassette", "genre":"El", "name": "Blue Lines", "img": "img/cassettes/bluelines_front.jpg", "price": "95 рублей"},
{"id": "el_21", "type": "Cassette", "genre":"El", "name": "Post", "img": "img/cassettes/post_front.jpg", "price": "175 рублей"},
{"id": "el_22", "type": "Cassette", "genre":"El", "name": "Remain In Light", "img": "img/cassettes/remaininalight-front.jpg", "price": "65 рублей"},
{"id": "el_23", "type": "DVD", "genre":"Rock00", "name": "Stop The Clocks", "img": "img/DVD/clocks_front.jpg", "price": "375 рублей"},
{"id": "el_24", "type": "DVD", "genre":"Rock00", "name": "A Rush Of The Blood To The Head", "img": "img/DVD/robth_front.jpg", "price": "215 рублей"},
{"id": "el_25", "type": "DVD", "genre":"Rock00", "name": "Standings On The Shoulders Of Giants", "img": "img/DVD/standing_front.jpg", "price": "145 рублей"},
{"id": "el_26", "type": "DVD", "genre":"Rock00", "name": "Up The Bracket", "img": "img/DVD/upthebracket-front.jpg", "price": "40 рублей"},
{"id": "el_27", "type": "DVD", "genre":"Rock00", "name": "Hail To The Thief", "img": "img/DVD/hail_front.jpg", "price": "270 рублей"},
{"id": "el_28", "type": "DVD", "genre":"Rock00", "name": "Toxicity", "img": "img/DVD/toxicity_front.jpg", "price": "179 рублей"},
{"id": "el_29", "type": "DVD", "genre":"Rock00", "name": "American Idiot", "img": "img/DVD/ai_front.jpg", "price": "235 рублей"},
];

